export const PERMISSIONS = {
  FULL_ACCESS: 'FULL_ACCESS',

  VIEW_PERMISSION: 'VIEW_PERMISSION',
  MY_PERMISSION: 'MY_PERMISSION',

  VIEW_ADDRESS: 'VIEW_ADDRESS',
  MY_ADDRESS: 'MY_ADDRESS',
  CREATE_ADDRESS: 'CREATE_ADDRESS',
  UPDATE_ADDRESS: 'UPDATE_ADDRESS',
  DELETE_ADDRESS: 'DELETE_ADDRESS',

  VIEW_APPOINTMENT: 'VIEW_APPOINTMENT',
  MY_APPOINTMENT: 'MY_APPOINTMENT',
  CREATE_APPOINTMENT: 'CREATE_APPOINTMENT',
  UPDATE_APPOINTMENT: 'UPDATE_APPOINTMENT',
  DELETE_APPOINTMENT: 'DELETE_APPOINTMENT',

  VIEW_ATTRIBUTE: 'VIEW_ATTRIBUTE',
  CREATE_ATTRIBUTE: 'CREATE_ATTRIBUTE',
  UPDATE_ATTRIBUTE: 'UPDATE_ATTRIBUTE',
  DELETE_ATTRIBUTE: 'DELETE_ATTRIBUTE',

  VIEW_ATTRIBUTE_VALUE: 'VIEW_ATTRIBUTE_VALUE',
  CREATE_ATTRIBUTE_VALUE: 'CREATE_ATTRIBUTE_VALUE',
  UPDATE_ATTRIBUTE_VALUE: 'UPDATE_ATTRIBUTE_VALUE',
  DELETE_ATTRIBUTE_VALUE: 'DELETE_ATTRIBUTE_VALUE',

  VIEW_BLOG: 'VIEW_BLOG',
  CREATE_BLOG: 'CREATE_BLOG',
  UPDATE_BLOG: 'UPDATE_BLOG',
  DELETE_BLOG: 'DELETE_BLOG',

  VIEW_BOOKING: 'VIEW_BOOKING',
  MY_BOOKING: 'MY_BOOKING',
  CREATE_BOOKING: 'CREATE_BOOKING',
  UPDATE_BOOKING: 'UPDATE_BOOKING',
  DELETE_BOOKING: 'DELETE_BOOKING',

  VIEW_CATEGORY: 'VIEW_CATEGORY',
  CREATE_CATEGORY: 'CREATE_CATEGORY',
  UPDATE_CATEGORY: 'UPDATE_CATEGORY',
  DELETE_CATEGORY: 'DELETE_CATEGORY',

  VIEW_CONVERSION_UNIT: 'VIEW_CONVERSION_UNIT',
  CREATE_CONVERSION_UNIT: 'CREATE_CONVERSION_UNIT',
  UPDATE_CONVERSION_UNIT: 'UPDATE_CONVERSION_UNIT',
  DELETE_CONVERSION_UNIT: 'DELETE_CONVERSION_UNIT',

  VIEW_FILE: 'VIEW_FILE',
  MY_FILE: 'MY_FILE',
  CREATE_FILE: 'CREATE_FILE',
  UPDATE_FILE: 'UPDATE_FILE',
  DELETE_FILE: 'DELETE_FILE',

  VIEW_ORDER_DETAIL: 'VIEW_ORDER_DETAIL',
  MY_ORDER_DETAIL: 'MY_ORDER_DETAIL',
  CREATE_ORDER_DETAIL: 'CREATE_ORDER_DETAIL',
  UPDATE_ORDER_DETAIL: 'UPDATE_ORDER_DETAIL',
  DELETE_ORDER_DETAIL: 'DELETE_ORDER_DETAIL',

  VIEW_ORDER_SHIPPING: 'VIEW_ORDER_SHIPPING',
  CREATE_ORDER_SHIPPING: 'CREATE_ORDER_SHIPPING',
  UPDATE_ORDER_SHIPPING: 'UPDATE_ORDER_SHIPPING',
  DELETE_ORDER_SHIPPING: 'DELETE_ORDER_SHIPPING',

  VIEW_ORDER: 'VIEW_ORDER',
  MY_ORDER: 'MY_ORDER',
  CREATE_ORDER: 'CREATE_ORDER',
  UPDATE_ORDER: 'UPDATE_ORDER',
  DELETE_ORDER: 'DELETE_ORDER',
  SET_ORDER_STATUS: 'SET_ORDER_STATUS',

  VIEW_PRODUCT: 'VIEW_PRODUCT',
  CREATE_PRODUCT: 'CREATE_PRODUCT',
  UPDATE_PRODUCT: 'UPDATE_PRODUCT',
  DELETE_PRODUCT: 'DELETE_PRODUCT',

  VIEW_REVIEW: 'VIEW_REVIEW',
  CREATE_REVIEW: 'CREATE_REVIEW',
  UPDATE_REVIEW: 'UPDATE_REVIEW',
  DELETE_REVIEW: 'DELETE_REVIEW',

  VIEW_ROLE: 'VIEW_ROLE',
  MY_ROLE: 'MY_ROLE',
  CREATE_ROLE: 'CREATE_ROLE',
  UPDATE_ROLE: 'UPDATE_ROLE',
  DELETE_ROLE: 'DELETE_ROLE',

  VIEW_UNIT: 'VIEW_UNIT',
  CREATE_UNIT: 'CREATE_UNIT',
  UPDATE_UNIT: 'UPDATE_UNIT',
  DELETE_UNIT: 'DELETE_UNIT',

  VIEW_USER: 'VIEW_USER',
  MY_USER: 'MY_USER',
  CREATE_USER: 'CREATE_USER',
  UPDATE_USER: 'UPDATE_USER',
  DELETE_USER: 'DELETE_USER',

  VIEW_VARIANT: 'VIEW_VARIANT',
  CREATE_VARIANT: 'CREATE_VARIANT',
  UPDATE_VARIANT: 'UPDATE_VARIANT',
  DELETE_VARIANT: 'DELETE_VARIANT',
};

export const ALL_USER_PERMISSIONS = [
  // PERMISSIONS.FULL_ACCESS,

  PERMISSIONS.MY_APPOINTMENT,
  PERMISSIONS.MY_BOOKING,
  PERMISSIONS.MY_FILE,
  PERMISSIONS.MY_ORDER_DETAIL,
  PERMISSIONS.MY_ORDER,
  PERMISSIONS.MY_ROLE,
  PERMISSIONS.MY_USER,

  PERMISSIONS.VIEW_CATEGORY,
  PERMISSIONS.VIEW_BLOG,
  PERMISSIONS.VIEW_REVIEW,
  PERMISSIONS.VIEW_PRODUCT,
  PERMISSIONS.VIEW_CONVERSION_UNIT,
  PERMISSIONS.VIEW_UNIT,

  PERMISSIONS.CREATE_APPOINTMENT,
  PERMISSIONS.CREATE_BOOKING,
];
